name: verify

on:
  pull_request: #pull request to master: execute tf plan
    branches: [main]
    paths:
      - "test/*"

  push: #push to master: execute tf apply
    branches: [main]
    paths:
      - "test/*"

jobs: 
  test: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: verify
        working-directory: test
        run: cat test.sh
