name: verify

on:
  pull_request: #pull request to master: execute tf plan
    branches: [main]

  push: #push to master: execute tf apply
    branches: [main]
    paths:
      - "test/*"

jobs: 
  test: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: 確認
        run: echo ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' && 'main' || github.event.pull_request.head.sha }}
      - name: verify
        working-directory: test
        run: cat test.sh
